### ISSUE TITLE
Want to extract telugu bible

### ISSUE THREAD

**Issue by Anudeep0978** [martijnlentink/propresenter-custom-bibles#13]
Hi Martjin, 
As per the given code it is to extract dutch language bible, but am  looking to extract telugu language bible. Language code as per the read me "te", and as per bible_import.py telugu language version code is "1737" after executing this bible_import.py ,.. After applying these changes I executed it but still am getting dutch language bible. Can you please help me in extracting the telugu language bible.

**Comment by disguisedshadow** [comment]
the three Letter code for Telugu is "tel" not "te". Try this

**Comment by martijnlentink** [comment]
It seems like you tried running the Python code. I've updated the readme could you check it and try running one of the binaries instead?

**Comment by martijnlentink** [comment]
Closed due to inactivity
