### ISSUE TITLE
version 2024-04-05. can't download specific bibile 

### ISSUE THREAD

**Issue by Hookist** [martijnlentink/propresenter-custom-bibles#15]
version 2024-04-05
When I've tried to download all bible with ukranian translation I've faced an issue with specific one. 
Languange code : urk
scripture number : 1755
When I'm trying to download it then after some percentage the program close, but I've managed to record screen and do the screenshot of callstack

![Turkoniaka](https://github.com/martijnlentink/propresenter-custom-bibles/assets/18694597/c7e8b872-5163-467a-9fd7-593d57828ae6)

**Comment by martijnlentink** [comment]
Hi there,

Thank you for reporting this issue. I've looked at it and it appears that the verse labels that are returned by Bible.com are sometimes incorrect. For some of them these can be remediated by looking at the underlying class label like in ECC.5.19. This one returns the label `-` where it should be `19` (see https://www.bible.com/bible/1755/ECC.5).

But there are some more problematic situations like in JER.32 here the verses have labels like `(1)`, `(2)` etc. but these don't correspond to JER.32.1 and JER.32.2 but actually to JER.32.15 and JER.32.16 this might give some odd behavior (see https://www.bible.com/bible/1755/JER.32 and highlight to discover the underlying number)
![image](https://github.com/martijnlentink/propresenter-custom-bibles/assets/1891829/b045d9be-5d7f-418c-9659-86966f3028f0).

All in all, I'm updating the code to circumvent issues when the label is given in an incorrect format, but I'm guessing that for your situation the verses might be linked incorrectly and the outcome would be an inconsistent Bible export so please take that in mind. And then it comes down to contacting Bible.com and ask them to make changes such that the metadata is correct.

**Comment by martijnlentink** [comment]
I created a new release, you can download it [here](https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2024-04-28). Please let me know if this fixes somewhat of the issues you have.

**Comment by Hookist** [comment]
It works! Thanks! Awesome, good job! I haven't checked all the verses but al least the one that I've cheacked are the same with other translation. Should I close this issue?

**Comment by martijnlentink** [comment]
That is great to hear. I'll close the issue, if you run into anything else let me know 😄
