### ISSUE TITLE
New folder is created every restart

### ISSUE THREAD

**Issue by PA7RIK** [martijnlentink/propresenter-custom-bibles#17]
A new folder with uuid is created every time I restart ProPresenter. 
eg. 5f1bb711-2dcf-48a3-88b6-9f42ad715856
in here: %programdata%\RenewedVision\ProPresenter\Bibles
It's like sideloading the custom bible at every startup.
Is this normal operation?

**Comment by martijnlentink** [comment]
That is indeed the behaviour of sideload bibles on Windows. Which is far from optimal, the only alternative I can think of is overwriting a free bible from the bible store. I could look into that to prevent HDD memory leakage.

**Comment by PA7RIK** [comment]
Thanks for your quick response and your work on the bible converter.

**Comment by PA7RIK** [comment]
I tried to overwrite the custom bible on a free downloaded bible and it didn't work. I tried to download a free bible and then overwrite it with the files of another free bible. This was successful by modifying BibleData.proPref.
I noticed that the new free bibles are using <usx version="3.0"> and the custom bible uses 2.0. This could be the problem. Do you have any idea?

**Comment by martijnlentink** [comment]
The fact that the USX formats are different should not cause the issue.

I've made it work before I found out that sideloading was possible. It should work if you leave the `BibleData.proPref` untouched and change the USX files. I can't recall what the exact requirements were for it to work but my guess is that it worked if you changed the contents of the folder. As you can see the history of my repository it was actually my first approach as well https://github.com/martijnlentink/propresenter-custom-bibles/tree/15bb0dd4184a703d03725cd528f3e90cbcb9248c?tab=readme-ov-file#how-does-this-work

**Comment by martijnlentink** [comment]
Also I think it is important to delete the `sideload` directory for this to work.

**Comment by martijnlentink** [comment]
Okay I just checked what the process was. It is as follows:

1. Install a free bible
2. Remove the contents of the folder
3. Move the contents of the new bible to that folder
4. Adjust the `rvmetadata.xml` file such that the `abbreviation` tag matches the original free bible. And introduce a new tag `displayAbbreviation` which should be set to the actual new bibles abbreviation.

```xml
<abbreviation>BB</abbreviation>
  <displayAbbreviation>EBV24</displayAbbreviation>
```

Hope this works for you!

**Comment by PA7RIK** [comment]
Thank you very much, your method works! 
I didn't think that the `abbreviation` tag was checked by ProPresenter.
