### ISSUE TITLE
MSG(The Message) Translation (Matthew Chapter 1) issue

### ISSUE THREAD

**Issue by Anghex30** [martijnlentink/propresenter-custom-bibles#18]
The text on chapter 1 verse 2 to verse 11 is not right it only contains the text "2-6" and "6-11"

I encounter the same issue on MSG, MBB05, MBBTAG12

but all other translations are good

please check attached image for your reference
![Capture](https://github.com/martijnlentink/propresenter-custom-bibles/assets/67251778/2c11916e-eba8-40b9-b024-98f50cd65e88)

thank you

**Comment by martijnlentink** [comment]
Thank you for bringing this to my attention. I was able to reproduce the bug and fix it. I've created a [new release](https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2024-05-04), please check and let me know if this fixes it for you 😄

**Comment by Anghex30** [comment]
It works, thank you
