### ISSUE TITLE
Contextual Search Feature Not Working

### ISSUE THREAD

**Issue by seyiadesigbin** [martijnlentink/propresenter-custom-bibles#22]
Hi @martijnlentink , thank you so much for this solution.. 🙏🏼

I was able to install the NKJV version successfully. Unfortunately, I realized that the "_contextual search_" feature does not work. You get a "_No Search Results_" message. After doing some deep-dive, I realized that this is because the "_SearchIndex_" folder is not included in the downloaded files for the translation.

Below is a snapshot of the result gotten.

![image](https://github.com/martijnlentink/propresenter-custom-bibles/assets/35711100/08621f79-a8cf-45c5-8180-a9b329eee386)

However, after some troubleshooting, I was able to get it to work by copy the "SearchIndex" folder from the KJV version which I installed directly from ProPresenter's interface. Apparently, it seems the SearchIndex config for a particular translation can work for other translations, provided they are the same language.

Thank you so much.

**Comment by martijnlentink** [comment]
Hi @seyiadesigbin,

Thank you for taking the time for noting this. It indeed is the case that there is no SearchIndex generated. I doubt though that simply copying over the folder would resolve it for every translation though. We still have an open issue #5 which raised the issue for generating an search index. What I mentioned there; there currently is no Python implementation available sadly. Someone has to take some time to port the .NET implementation for it to work.

I am closing this issue and progress on this will be tracked on #5
