### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by frozenade** [martijnlentink/propresenter-custom-bibles#24]
Hi, I got this error after I chose **Overwrite** option:

```
Traceback (most recent call last):
  File "bible_import.py", line 475, in <module>
  File "bible_import.py", line 381, in overwrite_free_bible
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Labcom\\AppData\\Local\\Temp\\_MEI213642\\available_bibles.json'
[12096] Failed to execute script 'bible_import' due to unhandled exception!
```

Is there something missing?

**Comment by martijnlentink** [comment]
Hi, thanks for reporting this. No, you didn't miss anything, I did when creating a new binary. Thanks for reporting this. I am fixing this and creating a new binary ASAP.

**Comment by martijnlentink** [comment]
@frozenade could you check [the new release](https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2024-07-17) if this fixes your crash?

**Comment by frozenade** [comment]
Yes, it already fixed now. Thanks.
