### ISSUE TITLE
Feature that will allow to adjust Bible verse numbering

### ISSUE THREAD

**Issue by AlphaHasher** [martijnlentink/propresenter-custom-bibles#27]
Hello,

Similar to your initial problem where the Pro7 team would not want to add a Bible translation, we have a similar issue. I am in a slavic-english church and on the screen we put up both Russian and an English translation. The issue comes into play when the preacher cites a passage from Psalms for example. https://www.ph4.org/btraduk_ruennum.php . Using this guide you can see how the numbering of verses between the English and Russian Bible differs, especially in the Psalms.

I looked into how your code takes the scriptures and converts them into the USX format and then into their rvbible format.

I am currently trying to write a script that will take the chapter and verse numbers and adjust them to the guide so that the translations line up on the screen. Yes I am aware that this will cause the text to be the same but the numbering will be off for the English translation but I think that this is a good comprise

Would you @martijnlentink be willing to help?

**Comment by AlphaHasher** [comment]
Yesterday I was able to write a script that did this. You can find it [here](https://github.com/AlphaHasher/propresenter-english-to-russian-translation-converter). This project would not have been possible without your help! Thanks!

**Comment by martijnlentink** [comment]
Wow you finished that rather quick! Cheers!
