### ISSUE TITLE
Mac - incorrect chapter sorting

### ISSUE THREAD

**Issue by AlphaHasher** [martijnlentink/propresenter-custom-bibles#3]
Hello, I love this script however I found an issue l.

![Image 2-18-24 at 1.14 PM.jpg](https://github.com/martijnlentink/propresenter-custom-bibles/assets/33443001/e0a2c736-f8d6-4206-8d7a-c5935bfcb684)

The chapters are not sorted.

Mac version: Sonoma 14.2.1
ProPresenter: 7.15

**Comment by martijnlentink** [comment]
Hi there, good to hear that it works for you. I've had that issue as well earlier, I can't recall how I fixed it though. For some reason it performs sorting alphabetically in this instance instead of numerically. I'll have a look and see if I can find what's wrong here.

**Comment by martijnlentink** [comment]
I've had a look. It appears to be the case that Windows version of ProPresenter performs sorting on chapters, whereas the Mac version doesn't. I just pushed changes that fixes this, I'll create binaries for them tomorrow.

**Comment by martijnlentink** [comment]
New binaries are released. Could you check if the order now appears correct?
