### ISSUE TITLE
[KeyError: 'offline'] Not able to download the bible

### ISSUE THREAD

**Issue by nani-samireddy** [martijnlentink/propresenter-custom-bibles#30]
#### Downloaded the latest version for mac and ran the file and encountered with the following error

<img width="1363" alt="Screenshot 2024-09-10 at 11 23 39 PM" src="https://github.com/user-attachments/assets/396e1f07-4744-4524-85ca-3de9c1a1c077">

**Comment by martijnlentink** [comment]
Hi @nani-samireddy,

Thank you for taking the time reporting this. I think I know what is the issue here, I'll see if I can fix this soon.

**Comment by martijnlentink** [comment]
Please try the new release and let me know if this fixes your issue. I'm still working on a better solution. https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2024-09-18-pre
