### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by yuguilley** [martijnlentink/propresenter-custom-bibles#32]
Hi friend this no work, 
<img width="559" alt="image" src="https://github.com/user-attachments/assets/7097416c-5180-4f46-b25c-b24eb40a5579">

Thanks.

**Comment by martijnlentink** [comment]
Please try the pre-release and let me know if this works for you.
https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2024-09-18-pre

**Comment by yuguilley** [comment]
No working  

1. remove the macOS Gatekeeper quarantine attribute.
![Artboard Copy](https://github.com/user-attachments/assets/693c8a17-9f7a-4d9a-ab70-53f8df020db3)

2. open bible_import
![Artboard](https://github.com/user-attachments/assets/7f24f566-9907-4ba3-a3f9-d1df8717327e)

**Comment by martijnlentink** [comment]
I see you're running on old Mac CPU. I don't have a build for that, please run python directly from this branch https://github.com/martijnlentink/propresenter-custom-bibles/tree/fix/30-missing-offline-bible

**Comment by yuguilley** [comment]
Oh yes, only work on Mac with Apple Silicone
Thanks, thanks 💯
