### ISSUE TITLE
MBBTAG05 NOT WORKING IN SCRIPTURE LOOKUP

### ISSUE THREAD

**Issue by Josh416-cmyk** [martijnlentink/propresenter-custom-bibles#33]
MBBTAG 2005 and MAAYONG BALITA is not working in scripture lookup in pro presenter can you please help me

**Comment by martijnlentink** [comment]
Hi @Josh416-cmyk,

I've investigated this and the issue appears to be improper chapter numbering in some of these books. I'm working on a solution for this. To be continued

**Comment by Josh416-cmyk** [comment]
thank you sir salute

**Comment by martijnlentink** [comment]
Hi @Josh416-cmyk,

Please could you check with newest release if it is working now 😸

**Comment by Josh416-cmyk** [comment]
hello sir how about generatec search index it will work?

**Comment by Josh416-cmyk** [comment]
hi martin can i ask question if it is possible to rename display reference
like (NIV) to (New International Version)

it is possible with custom rv Bibles that can edit display bible reference
name?

thank you martin much appreciated your response ❤️❤️❤️

**Comment by martijnlentink** [comment]
> hello sir how about generatec search index it will work?

No, there is no work done on search index generation.



> hi martin can i ask question if it is possible to rename display reference like (NIV) to (New International Version)

Yes this is possible, the method differs on platform. But for the sake of simplicity I assume you are using Windows. Go to `%programdata%\RenewedVision\ProPresenter\Bibles`, chose the folder where your bible is stored in (by either checking the `BibleData.proPref` file, or checking the `rvmetadata.xml` file inside the folders). Change the `displayAbbreviation` value in the `rvmetadata.xml` file. That should do it.

**Comment by Josh416-cmyk** [comment]
its not working.. after i've renamed it to rv metadata it will creating
another folder contains rv.metadata
