### ISSUE TITLE
[ERROR] IT WON'T LET ME DOWNLOAD IN THE SPANISH LANGUAGE SPAIN 

### ISSUE THREAD

**Issue by JUAN88190** [martijnlentink/propresenter-custom-bibles#40]
When I select the Spanish language, the results I get are not correct. I see the Latin American version and the one I need is the Spanish version.
![Captura](https://github.com/user-attachments/assets/dec819e9-2a5d-4dd3-b551-635c097b2dbc)

**Comment by martijnlentink** [comment]
Fixed in #42 will be fixed in next release. Sorry for this oversight.

**Comment by martijnlentink** [comment]
Newest release now out! [Click here to download](https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2025-01-02). Keen to hear if this fixes the issue!
